# 将静态内容部署到 GitHub Pages 的简易工作流程
name: VITE DEPLOY TEST

# on 字段指定触发 workflow 的条件
on:
  push:
    # 推送到指定分支时触发
    branches: [develop]

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 任务ID 单次部署的工作描述
  deploy:
    # 指定虚拟机环境 GitHub Actions 给我们提提供的运行环境主要有以下几种：
    # ubuntu-latest，ubuntu-18.04或ubuntu-16.04
    # windows-latest，windows-2019或windows-2016
    # macOS-latest或macOS-10.14
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout
        # 拉取 GitHub 仓库代码
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        # 设定 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install
        # 安装依赖
        run: pnpm install

      - name: Build
        # 打包
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署打包目录
          folder: example/dist
          # 密钥名
          token: ${{ secrets.VITE_DEPLOY_TEST }}
          # 部署后提交到那个分支
          branch: gh-pages
